#! /bin/sh

echo "increasing m, n=400"
n=200
for aog in 4 8 16 32 64; do
	m=$((aog*n))
	./evalRand $n $m
done

echo "increasing n, avgOutDeg=16"
aog=16
for n in 50 100 200 400 800 ; do
	m=$((aog*n))
	./evalRand $n $m
done
